### ISSUE TITLE
Lauching applications on Windows without charmrun fails with “OSError: exception: stack overflow”

### ISSUE THREAD

**Issue by chjq201410695** [UIUC-PPL/charmpy#18]
The problem is same as title mentioned. So I Wondering where is wrong, and how can I correct it.

I have installed charmpy and cython via pip accroding to toturial.

My environment:
Win10,  python 3.5,  jupyter notebook.

**Comment by juanjgalvez** [comment]
The issue might be that you are running from a jupyter notebook, since CharmPy is untested (and likely as yet unsupported) in an interactive environment.

Can you test launching from the command line using charmrun? Go into the directory where the example program is located, and use a command like (make sure the name of the script matches with yours):
> python -m charmrun.start +p4 hello.py

**Comment by juanjgalvez** [comment]
Actually, this is a bug when running on Windows without `charmrun`.

If you run without charmrun it should run but using only one process (the current process). This works on Linux but not on Windows.

For now, my suggestion is to always use charmrun on Windows.

I will also separately submit a pull request so that applications can be launched with charmrun from an interactive session.

**Comment by juanjgalvez** [comment]
This has been fixed in a5667885578f37db5930fca494e4ec4e76e24921 and is in `0.10.1` release.
